#!/bin/bash

source /etc/rotatewallpaper.conf
if [[ -e $HOME/.config/rotatewallpaper.conf ]]
then
	source $HOME/.config/rotatewallpaper.conf
fi

if [[ -z "$1" ]]
then
	wpdir=$WALLPAPER_DIRECTORY
else
	wpdir=$1
fi
file=$(ls $wpdir/* | shuf | tail -1)
chwallpaper-$XDG_SESSION_DESKTOP $file
